# DATABASE PRODUCTION
spring.datasource.url=${DB_URL:${DATABASE_URL}}
spring.datasource.username=${DB_USERNAME:${DATABASE_USERNAME}}
spring.datasource.password=${DB_PASSWORD:${DATABASE_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA PRODUCTION
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FLYWAY PRODUCTION
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# CONNECTION POOL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# LOGGING
logging.level.root=INFO
logging.level.id.ac.ui.cs.advprog=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN