spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# JWT SECRET FOR TEST
JWT_SECRET=c3VwZXJzZWNyZXRzdXBlcnNlY3JldHN1cGVyc2VjcmV0

# DISABLE FLYWAY FOR TEST
spring.flyway.enabled=false