# DATABASE LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5435/mysawit_payment
spring.datasource.username=payment_user
spring.datasource.password=paymentpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA DEV
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# FLYWAY FOR LOCAL
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration