spring.datasource.url=jdbc:postgresql://localhost:5435/mysawit_payment_test
spring.datasource.username=payment_user
spring.datasource.password=paymentpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# JWT SECRET FOR TEST
JWT_SECRET=c3VwZXJzZWNyZXRzdXBlcnNlY3JldHN1cGVyc2VjcmV0

# FLYWAY FOR TEST
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration