spring.application.name=mysawit-payment
server.port=8002
jwt.secret=${JWT_SECRET}

spring.profiles.active=local

# JPA / HIBERNATE
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# XENDIT
xendit.secret-key=${XENDIT_SECRET_KEY}
xendit.base-url=https://api.xendit.co

payment.gateway=xendit